### ISSUE TITLE
Django girls hack no longer needed

### ISSUE THREAD

**Issue by helenst** [pythonanywhere/helper_scripts#10]
There's a hack in the DjangoProject class to install Django 1.x by default while Django Girls upgrades to 2.x. (https://github.com/pythonanywhere/helper_scripts/blob/master/pythonanywhere/django_project.py#L34) This has happened now - see https://github.com/DjangoGirls/tutorial/pull/1282 so the hack is not needed any more.

(This caught us out at a workshop today when we had an incorrectly named requirements.txt and ended up with 1.x in our venv)

**Comment by hjwp** [comment]
thanks Helen!  taking a look...

**Comment by hjwp** [comment]
didn't know a requirement.txt is recommended now!  that's cool...

**Comment by pythonanywhere** [comment]
OK, that's all deployed.   I accidentally closed the issue -- I've re-opened it, would be grateful for any comments as to whether it all works OK :-)
