### ISSUE TITLE
travis.

### ISSUE THREAD

**Issue by hjwp** [pythonanywhere/helper_scripts#12]

**Comment by pythonanywhere** [comment]
Hmm, Travis quite expensive for non-open-source projects and while this repo is OS, most of ours aren't.   Might hold off on this.

**Comment by hjwp** [comment]
i don't understand?  does signing up on the free plan to get this one working commit pythonanywhere to something?

**Comment by pythonanywhere** [comment]
The signup appears to be per-GitHub account rather than per-repository, so it's unclear without spending time digging through their T&Cs what we need to do.   Not something we can jump into.

**Comment by hjwp** [comment]
I've got a travis account, they never asked me for any money just because I have private repos???  they don't even have my credit card details as far as I know?

**Comment by hjwp** [comment]
$NEWWORK has tons of private repos and also a travis account which is only used for free/open source stuff.

**Comment by hjwp** [comment]
did you make sure to go to https://travis-ci.org, not https://travis-ci.com ?

**Comment by conradho** [comment]
thanks @hjwp, we've added travis CI!

**Comment by hjwp** [comment]
:party: :checkered_flag:
