### ISSUE TITLE
upgrade to 3.7 and tell all the old-image stragglers to use "pyenv" to install 3.7 into their home folders

### ISSUE THREAD

**Issue by hjwp** [pythonanywhere/helper_scripts#19]
https://github.com/pyenv/pyenv

**Comment by millenniumhand** [comment]
![refactoring cat](https://geekshumor.com/wp-content/uploads/2013/09/Code-Refactoring.gif)

**Comment by conradho** [comment]
@hjwp we have added CI tests for running this code base on python3.7. We are currently keeping support (and testing) for python3.5, python3.6, python3.7 for now.
